### ISSUE TITLE
Doesn't pick up Spotify

### ISSUE THREAD

**Issue by AimPizza** [Jax-Core/ModularPlayers#1]
The player says that nothing is playing. pls help
![Bild_2021-08-15_184259](https://user-images.githubusercontent.com/64905268/129485843-394e2d4b-f023-4d0e-9e82-fe91daa1559c.png)

**Comment by EnhancedJax** [comment]
You have to install spicetify-cli for it to work.

**Comment by TheDrone7** [comment]
I had the same issue. I tried installing spicetify-cli but still no luck.

![image](https://user-images.githubusercontent.com/38010647/129554206-109f5174-79a8-4823-b2f9-731c6c43e59f.png)

**Comment by EnhancedJax** [comment]
Please read this guide here. 
https://github.com/khanhas/spicetify-cli/wiki/Guide-for-Rainmeter-user

**Comment by TheDrone7** [comment]
I tried that and now Spotify itself isn't loading up.

**Comment by TheDrone7** [comment]
I restored the backup and Spotify is starting now. But when I apply the changes Spotify just shows a blank white screen.

**Comment by EnhancedJax** [comment]
If you spotify is blank after theming with spicetify:

-uninstall spotify
-delete both spicetify folders in your user folder (.spicetify, and spicetify-cli)
-delete your spotify folder in `%appdata%\local`
-delete everything in `%temp%`

-install this ver of spotify 
> check embed
-then create a folder in `%appdata%local/spotify`
call it Update

-and set the user group permissions so that trusted installer and system have permissions blocked

-open powershell and paste this into it 
`Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression`

-type spicetify and hit enter once

-run this `spicetify backup apply enable-devtool`

-close spotify


Now run the codes from here: https://github.com/khanhas/spicetify-cli/wiki/Guide-for-Rainmeter-user

Make sure you have put your theme (https://github.com/morpheusthewhite/spicetify-themes/tree/master) into the theme folder in %user%.spicetify/themes, DO THIS BEFORE THE COMMANDS. If you are using a theme such as dribbblish, that has a custom .js, simply move it from themes folder to extensions folder. Or use the built in .psi install, however simply moving the .js is easiest.

**Comment by volktwins** [comment]
I think "https://github.com/khanhas/spicetify-cli/wiki/Guide-for-Rainmeter-user" is removed what should i do next?
