### ISSUE TITLE
Download Failed - Virus Detected

### ISSUE THREAD

**Issue by NotIPlayForFun** [Jax-Core/ModularPlayers#5]
Having this problem when attempting to download ModularPlayers_v1.3.rmskin. Works fine with other files, such as JaxCore etc. Tried on Chrome aswell as Microsoft Edge, seems to not be browser related.
EDIT: I should add that I already have JaxCore and ModularPlayers installed, however, in Modular Players, under info, it shows "One upadete ahead... Currently on a beta build for ModularPlayers" and when clicking on "One update ahead" it directed me here.

**Comment by EnhancedJax** [comment]
One update ahead should be a version error, so just ignore that. For the virus, it is mostly due to the skin having an autohotkey executable in it, and it got flagged as a potential threat. The executable is used to run hotkey commands, in the case to install core automatically. If it blocks you from downloading, you can right click and select download anyways is most browsers. Hope this helps.

**Comment by NotIPlayForFun** [comment]
Alright, Thank you :)
